# Generated by Django 4.0.3 on 2022-03-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
