# Generated by Django 4.0.3 on 2022-03-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0002_scraperuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
