# Generated by Django 4.0.3 on 2022-05-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0003_alter_scraperuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_url', models.CharField(max_length=250)),
                ('caption', models.CharField(max_length=1000)),
                ('shortcode', models.CharField(max_length=60)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigate.user')),
            ],
        ),
    ]
