# Generated by Django 4.0.3 on 2022-05-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0004_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='user_id',
            new_name='user',
        ),
    ]
