# Generated by Django 4.0.3 on 2022-05-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0005_rename_user_id_publication_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigate.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigate.user')),
            ],
        ),
    ]
