# Generated by Django 4.0.3 on 2022-05-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0006_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_following', models.IntegerField()),
                ('user_followed', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
