# Generated by Django 4.0.3 on 2022-05-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0007_relationusers_rename_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationusers',
            name='user_followed',
        ),
        migrations.RemoveField(
            model_name='relationusers',
            name='user_following',
        ),
        migrations.AddField(
            model_name='relationusers',
            name='user_following',
            field=models.ManyToManyField(to='navigate.user'),
        ),
    ]
