# Generated by Django 4.0.3 on 2022-05-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0008_remove_relationusers_user_followed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_following',
            field=models.ManyToManyField(to='navigate.user'),
        ),
        migrations.DeleteModel(
            name='RelationUsers',
        ),
    ]
