# Generated by Django 4.0.3 on 2022-05-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0009_user_user_following_delete_relationusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(to='navigate.public')),
            ],
        ),
    ]
