# Generated by Django 4.0.3 on 2022-05-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0011_delete_article_delete_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='shortcode',
        ),
    ]
