# Generated by Django 4.0.3 on 2022-05-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0013_comment_comment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
