# Generated by Django 4.0.3 on 2022-05-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0014_publication_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
