# Generated by Django 4.0.3 on 2022-05-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0015_user_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
