# Generated by Django 4.0.3 on 2022-05-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0016_comment_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_following',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_posts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_link',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_description',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_other_url',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_public_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
