# Generated by Django 4.0.3 on 2022-05-30 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0017_user_number_followers_user_number_following_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=600, null=True)),
                ('content', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigate.image'),
        ),
    ]
