# Generated by Django 4.0.3 on 2022-05-30 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0018_image_alter_user_profile_picture_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_link',
        ),
    ]
