# Generated by Django 4.0.3 on 2022-05-30 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0019_remove_user_profile_picture_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigate.image'),
        ),
    ]
