# Generated by Django 4.0.3 on 2022-05-30 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0020_user_profile_picture_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('variable', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigate.catalog')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigate.catalog'),
        ),
    ]
