# Generated by Django 4.0.3 on 2022-05-30 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0021_catalog_image_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_link',
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigate.user'),
        ),
    ]
