# Generated by Django 4.0.3 on 2022-05-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0023_alter_catalog_description_alter_catalog_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='variable',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
