# Generated by Django 4.0.3 on 2022-05-31 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0024_alter_catalog_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigate.publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='number_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(null=True),
        ),
    ]
