# Generated by Django 4.0.3 on 2022-07-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0025_image_publication_publication_number_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(null=True),
        ),
    ]
