# Generated by Django 4.0.3 on 2022-05-20 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navigate', '0015_user_is_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('word_type', models.CharField(max_length=250)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigate.comment')),
            ],
        ),
    ]
