# Generated by Django 4.0.3 on 2022-05-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_type',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
