# Generated by Django 4.0.3 on 2022-05-20 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_alter_word_word_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.word')),
            ],
        ),
    ]
