# Generated by Django 4.0.3 on 2022-06-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_triplet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Triplet',
            new_name='Clause',
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
