# Generated by Django 4.0.3 on 2022-06-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0004_rename_triplet_clause_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=500),
        ),
    ]
