# Generated by Django 4.0.3 on 2022-06-02 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0025_image_publication_publication_number_likes_and_more'),
        ('analyze', '0007_remove_word_comment_word_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='comment',
        ),
        migrations.CreateModel(
            name='WordInComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigate.comment')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.word')),
            ],
        ),
    ]
