# Generated by Django 4.0.3 on 2022-06-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0025_image_publication_publication_number_likes_and_more'),
        ('analyze', '0008_remove_word_comment_wordincomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigate.catalog')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.word')),
            ],
        ),
    ]
